/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChallengeType = { 'timeManagement' : null } |
  { 'socialIsolation' : null } |
  { 'mentalHealth' : null } |
  { 'bullying' : null } |
  { 'academicPressure' : null } |
  { 'financialStress' : null } |
  { 'onlineLearning' : null };
export interface LeadershipWordSubmission {
  'why' : string,
  'roleModel' : string,
  'word' : string,
  'actionStep' : string,
  'resilienceExample' : string,
}
export interface ResilientLeadershipActivity {
  'microSolution' : string,
  'customChallenge' : [] | [string],
  'villainResponse' : string,
  'challengeType' : [] | [ChallengeType],
  'heroicResponse' : string,
  'protectiveFactor' : string,
}
export interface _SERVICE {
  'getAllLeadershipWordSubmissions' : ActorMethod<
    [],
    Array<[Principal, LeadershipWordSubmission]>
  >,
  'getAllMicroSolutions' : ActorMethod<[], Array<ResilientLeadershipActivity>>,
  'getLeadershipWordCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'getTopLeadershipWords' : ActorMethod<[], Array<[string, bigint]>>,
  'submitLeadershipWord' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitResilientLeadershipActivity' : ActorMethod<
    [[] | [ChallengeType], [] | [string], string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];