/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeadershipWordSubmission = IDL.Record({
  'why' : IDL.Text,
  'roleModel' : IDL.Text,
  'word' : IDL.Text,
  'actionStep' : IDL.Text,
  'resilienceExample' : IDL.Text,
});
export const ChallengeType = IDL.Variant({
  'timeManagement' : IDL.Null,
  'socialIsolation' : IDL.Null,
  'mentalHealth' : IDL.Null,
  'bullying' : IDL.Null,
  'academicPressure' : IDL.Null,
  'financialStress' : IDL.Null,
  'onlineLearning' : IDL.Null,
});
export const ResilientLeadershipActivity = IDL.Record({
  'microSolution' : IDL.Text,
  'customChallenge' : IDL.Opt(IDL.Text),
  'villainResponse' : IDL.Text,
  'challengeType' : IDL.Opt(ChallengeType),
  'heroicResponse' : IDL.Text,
  'protectiveFactor' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllLeadershipWordSubmissions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, LeadershipWordSubmission))],
      ['query'],
    ),
  'getAllMicroSolutions' : IDL.Func(
      [],
      [IDL.Vec(ResilientLeadershipActivity)],
      ['query'],
    ),
  'getLeadershipWordCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTopLeadershipWords' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'submitLeadershipWord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitResilientLeadershipActivity' : IDL.Func(
      [
        IDL.Opt(ChallengeType),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeadershipWordSubmission = IDL.Record({
    'why' : IDL.Text,
    'roleModel' : IDL.Text,
    'word' : IDL.Text,
    'actionStep' : IDL.Text,
    'resilienceExample' : IDL.Text,
  });
  const ChallengeType = IDL.Variant({
    'timeManagement' : IDL.Null,
    'socialIsolation' : IDL.Null,
    'mentalHealth' : IDL.Null,
    'bullying' : IDL.Null,
    'academicPressure' : IDL.Null,
    'financialStress' : IDL.Null,
    'onlineLearning' : IDL.Null,
  });
  const ResilientLeadershipActivity = IDL.Record({
    'microSolution' : IDL.Text,
    'customChallenge' : IDL.Opt(IDL.Text),
    'villainResponse' : IDL.Text,
    'challengeType' : IDL.Opt(ChallengeType),
    'heroicResponse' : IDL.Text,
    'protectiveFactor' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllLeadershipWordSubmissions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, LeadershipWordSubmission))],
        ['query'],
      ),
    'getAllMicroSolutions' : IDL.Func(
        [],
        [IDL.Vec(ResilientLeadershipActivity)],
        ['query'],
      ),
    'getLeadershipWordCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTopLeadershipWords' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'submitLeadershipWord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitResilientLeadershipActivity' : IDL.Func(
        [
          IDL.Opt(ChallengeType),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };