/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChallengeType = IDL.Variant({
  'timeManagement' : IDL.Null,
  'socialIsolation' : IDL.Null,
  'mentalHealth' : IDL.Null,
  'bullying' : IDL.Null,
  'academicPressure' : IDL.Null,
  'financialStress' : IDL.Null,
  'onlineLearning' : IDL.Null,
});
export const ResilientLeadershipActivity = IDL.Record({
  'microSolution' : IDL.Text,
  'customChallenge' : IDL.Opt(IDL.Text),
  'villainResponse' : IDL.Text,
  'challengeType' : IDL.Opt(ChallengeType),
  'heroicResponse' : IDL.Text,
  'protectiveFactor' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const QuoteGenre = IDL.Variant({
  'starWars' : IDL.Null,
  'transformers' : IDL.Null,
  'batman' : IDL.Null,
  'threeKings' : IDL.Null,
  'kingsman' : IDL.Null,
  'darkKnightTrilogy' : IDL.Null,
  'avengers' : IDL.Null,
  'infinite' : IDL.Null,
  'warDogs' : IDL.Null,
});
export const Quote = IDL.Record({
  'movieReference' : IDL.Text,
  'quote' : IDL.Text,
  'genre' : QuoteGenre,
  'attribution' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMicroSolutions' : IDL.Func(
      [],
      [IDL.Vec(ResilientLeadershipActivity)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeadershipWordCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getNextActivity1Quote' : IDL.Func([], [Quote], []),
  'getNextActivity2Quote' : IDL.Func([], [Quote], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLeadershipWord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitResilientLeadershipActivity' : IDL.Func(
      [
        IDL.Opt(ChallengeType),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChallengeType = IDL.Variant({
    'timeManagement' : IDL.Null,
    'socialIsolation' : IDL.Null,
    'mentalHealth' : IDL.Null,
    'bullying' : IDL.Null,
    'academicPressure' : IDL.Null,
    'financialStress' : IDL.Null,
    'onlineLearning' : IDL.Null,
  });
  const ResilientLeadershipActivity = IDL.Record({
    'microSolution' : IDL.Text,
    'customChallenge' : IDL.Opt(IDL.Text),
    'villainResponse' : IDL.Text,
    'challengeType' : IDL.Opt(ChallengeType),
    'heroicResponse' : IDL.Text,
    'protectiveFactor' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const QuoteGenre = IDL.Variant({
    'starWars' : IDL.Null,
    'transformers' : IDL.Null,
    'batman' : IDL.Null,
    'threeKings' : IDL.Null,
    'kingsman' : IDL.Null,
    'darkKnightTrilogy' : IDL.Null,
    'avengers' : IDL.Null,
    'infinite' : IDL.Null,
    'warDogs' : IDL.Null,
  });
  const Quote = IDL.Record({
    'movieReference' : IDL.Text,
    'quote' : IDL.Text,
    'genre' : QuoteGenre,
    'attribution' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMicroSolutions' : IDL.Func(
        [],
        [IDL.Vec(ResilientLeadershipActivity)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeadershipWordCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getNextActivity1Quote' : IDL.Func([], [Quote], []),
    'getNextActivity2Quote' : IDL.Func([], [Quote], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLeadershipWord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitResilientLeadershipActivity' : IDL.Func(
        [
          IDL.Opt(ChallengeType),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };