/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChallengeType = { 'timeManagement' : null } |
  { 'socialIsolation' : null } |
  { 'mentalHealth' : null } |
  { 'bullying' : null } |
  { 'academicPressure' : null } |
  { 'financialStress' : null } |
  { 'onlineLearning' : null };
export interface LeadershipWordSubmission {
  'why' : string,
  'roleModel' : string,
  'word' : string,
  'actionStep' : string,
  'resilienceExample' : string,
}
export interface Quote {
  'movieReference' : string,
  'quote' : string,
  'genre' : QuoteGenre,
  'attribution' : string,
}
export type QuoteGenre = { 'starWars' : null } |
  { 'transformers' : null } |
  { 'batman' : null } |
  { 'threeKings' : null } |
  { 'kingsman' : null } |
  { 'darkKnightTrilogy' : null } |
  { 'avengers' : null } |
  { 'infinite' : null } |
  { 'warDogs' : null };
export interface ResilientLeadershipActivity {
  'microSolution' : string,
  'customChallenge' : [] | [string],
  'villainResponse' : string,
  'challengeType' : [] | [ChallengeType],
  'heroicResponse' : string,
  'protectiveFactor' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllActivity1Quotes' : ActorMethod<[], Array<Quote>>,
  'getAllActivity2Quotes' : ActorMethod<[], Array<Quote>>,
  'getAllLeadershipWordSubmissions' : ActorMethod<
    [],
    Array<[Principal, LeadershipWordSubmission]>
  >,
  'getAllMicroSolutions' : ActorMethod<[], Array<ResilientLeadershipActivity>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeadershipWordCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'getNextActivity1Quote' : ActorMethod<[], Quote>,
  'getNextActivity2Quote' : ActorMethod<[], Quote>,
  'getTopLeadershipWords' : ActorMethod<[], Array<[string, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'populateActivity1Quotes' : ActorMethod<[Array<Quote>], undefined>,
  'populateActivity2Quotes' : ActorMethod<[Array<Quote>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLeadershipWord' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitResilientLeadershipActivity' : ActorMethod<
    [[] | [ChallengeType], [] | [string], string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];