/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeadershipWordSubmission {
    why: string;
    roleModel: string;
    word: string;
    actionStep: string;
    resilienceExample: string;
}
export interface ResilientLeadershipActivity {
    microSolution: string;
    customChallenge?: string;
    villainResponse: string;
    challengeType?: ChallengeType;
    heroicResponse: string;
    protectiveFactor: string;
}
export enum ChallengeType {
    timeManagement = "timeManagement",
    socialIsolation = "socialIsolation",
    mentalHealth = "mentalHealth",
    bullying = "bullying",
    academicPressure = "academicPressure",
    financialStress = "financialStress",
    onlineLearning = "onlineLearning"
}
export interface backendInterface {
    getAllLeadershipWordSubmissions(): Promise<Array<[Principal, LeadershipWordSubmission]>>;
    getAllMicroSolutions(): Promise<Array<ResilientLeadershipActivity>>;
    getLeadershipWordCounts(): Promise<Array<[string, bigint]>>;
    getTopLeadershipWords(): Promise<Array<[string, bigint]>>;
    submitLeadershipWord(word: string, why: string, roleModel: string, resilienceExample: string, actionStep: string): Promise<void>;
    submitResilientLeadershipActivity(challengeType: ChallengeType | null, customChallenge: string | null, villainResponse: string, heroicResponse: string, protectiveFactor: string, microSolution: string): Promise<void>;
}
import type { ChallengeType as _ChallengeType, ResilientLeadershipActivity as _ResilientLeadershipActivity } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllLeadershipWordSubmissions(): Promise<Array<[Principal, LeadershipWordSubmission]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeadershipWordSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeadershipWordSubmissions();
            return result;
        }
    }
    async getAllMicroSolutions(): Promise<Array<ResilientLeadershipActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMicroSolutions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMicroSolutions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadershipWordCounts(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadershipWordCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadershipWordCounts();
            return result;
        }
    }
    async getTopLeadershipWords(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopLeadershipWords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopLeadershipWords();
            return result;
        }
    }
    async submitLeadershipWord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLeadershipWord(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLeadershipWord(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitResilientLeadershipActivity(arg0: ChallengeType | null, arg1: string | null, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitResilientLeadershipActivity(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitResilientLeadershipActivity(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_ChallengeType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChallengeType): ChallengeType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ResilientLeadershipActivity_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResilientLeadershipActivity): ResilientLeadershipActivity {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChallengeType]): ChallengeType | null {
    return value.length === 0 ? null : from_candid_ChallengeType_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    microSolution: string;
    customChallenge: [] | [string];
    villainResponse: string;
    challengeType: [] | [_ChallengeType];
    heroicResponse: string;
    protectiveFactor: string;
}): {
    microSolution: string;
    customChallenge?: string;
    villainResponse: string;
    challengeType?: ChallengeType;
    heroicResponse: string;
    protectiveFactor: string;
} {
    return {
        microSolution: value.microSolution,
        customChallenge: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.customChallenge)),
        villainResponse: value.villainResponse,
        challengeType: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.challengeType)),
        heroicResponse: value.heroicResponse,
        protectiveFactor: value.protectiveFactor
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timeManagement: null;
} | {
    socialIsolation: null;
} | {
    mentalHealth: null;
} | {
    bullying: null;
} | {
    academicPressure: null;
} | {
    financialStress: null;
} | {
    onlineLearning: null;
}): ChallengeType {
    return "timeManagement" in value ? ChallengeType.timeManagement : "socialIsolation" in value ? ChallengeType.socialIsolation : "mentalHealth" in value ? ChallengeType.mentalHealth : "bullying" in value ? ChallengeType.bullying : "academicPressure" in value ? ChallengeType.academicPressure : "financialStress" in value ? ChallengeType.financialStress : "onlineLearning" in value ? ChallengeType.onlineLearning : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResilientLeadershipActivity>): Array<ResilientLeadershipActivity> {
    return value.map((x)=>from_candid_ResilientLeadershipActivity_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ChallengeType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChallengeType): _ChallengeType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChallengeType | null): [] | [_ChallengeType] {
    return value === null ? candid_none() : candid_some(to_candid_ChallengeType_n9(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChallengeType): {
    timeManagement: null;
} | {
    socialIsolation: null;
} | {
    mentalHealth: null;
} | {
    bullying: null;
} | {
    academicPressure: null;
} | {
    financialStress: null;
} | {
    onlineLearning: null;
} {
    return value == ChallengeType.timeManagement ? {
        timeManagement: null
    } : value == ChallengeType.socialIsolation ? {
        socialIsolation: null
    } : value == ChallengeType.mentalHealth ? {
        mentalHealth: null
    } : value == ChallengeType.bullying ? {
        bullying: null
    } : value == ChallengeType.academicPressure ? {
        academicPressure: null
    } : value == ChallengeType.financialStress ? {
        financialStress: null
    } : value == ChallengeType.onlineLearning ? {
        onlineLearning: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
